### ISSUE TITLE
Have you reproduced this project on a real robot？

### ISSUE THREAD

**Issue by wallEVA96** [matval/WayFAST#1]
have you reproduced this project on a real robot？or why not add ROS interface for people development.

**Comment by matval** [comment]
Hello @wallEVA96, thank you for reaching out!
Yes, we reproduced this project on a real robot. We used a TerraSentia manufactured by EarthSense, and we used a Intel RealSense D435i as the visual sensor.
And thank you for the suggestion, I'll separate and organize our ROS code to share for development.

**Comment by Hello970** [comment]
Thanks for your wonderful work. Looking forward to your ROS code for development!
